# Statically link the CRT on Windows with MSVC toolchain
# (only in release mode)
[target.'cfg(all(windows, target_env = "msvc", not(debug_assertions)))']
rustflags = ["-C", "target-feature=+crt-static"]
